package org.test.parking.lot.domain;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import org.test.parking.exception.domain.RestrictedLotOperationException;
import org.test.parking.exception.domain.SlotNotFoundException;
import org.test.parking.session.domain.SlotStatus;

public class Level {

    private final int number;
    private final Map<Integer, Slot> slots = new HashMap<>();

    public Level(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public int addSlot(SlotType slotType) {
        //ASSUMPTION: slot id is generated by level and is unique within the level. It can be changed to global unique id generator if needed.
        int newSlotId = slots.size() + 1;
        Slot slot = new Slot(newSlotId, number, slotType);
        slots.put(slot.getId(), slot);
        return slot.getId();
    }

    public void removeSlot(int slotId) throws SlotNotFoundException, RestrictedLotOperationException{
        Slot slot = getSlotOrThrow(slotId);
        if (slot.isOccupied()) {
            throw new RestrictedLotOperationException(String.format("Slot with id [%d] in level [%d] is occupied and cannot be removed", slotId, number));
        }
        slots.remove(slotId);
    }

    public void occupySlot(int slotId) throws SlotNotFoundException, RestrictedLotOperationException {
        getSlotOrThrow(slotId)
            .occupy();
    }

    public void releaseSlot(int slotId) throws SlotNotFoundException, RestrictedLotOperationException {
        getSlotOrThrow(slotId)
            .release();
    }

    public Slot changeSlotStatus(Integer slotId, SlotStatus slotStatus) throws SlotNotFoundException, RestrictedLotOperationException {
        Slot slot = getSlotOrThrow(slotId);
        switch (slotStatus) {
            case AVAILABLE -> slot.release();
            case OCCUPIED -> slot.occupy();
            case UNAVAILABLE -> slot.markOutOfService();
        }
        return slot;
    }

    public Collection<Slot> getSlots() {
        return slots.values();
    }

    public boolean hasOccupiedSlots() {
        return slots.values().stream().anyMatch(Slot::isOccupied);
    }

    private Slot getSlotOrThrow(int slotId) throws SlotNotFoundException {
        Slot slot = slots.get(slotId);
        if (slot == null) {
            throw new SlotNotFoundException(String.format("Slot with id [%d] not found in level [%d]", slotId, number));
        }
        return slot;
    }
}
