package org.test.parking.domain.space;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.test.parking.domain.session.SlotStatus;
import org.test.parking.domain.vehicle.Vehicle;
import org.test.parking.exception.domain.RestrictedSlotOperationException;
import org.test.parking.exception.domain.SlotNotFoundException;

public class Level {

    private final int number;
    private final Map<Integer, Slot> slots = new HashMap<>();

    public Level(int number) {
        this.number = number;
    }

    public Slot addSlot(SlotType slotType) {
        //ASSUMPTION: slot id is generated by level and is unique within the level. It can be changed to global unique id generator if needed.
        int newSlotId = slots.size() + 1;
        Slot slot = new Slot(newSlotId, number, slotType);
        slots.put(slot.getId(), slot);
        return slot;
    }

    public Slot removeSlot(int slotId) throws SlotNotFoundException, RestrictedSlotOperationException{
        Slot slot = slots.get(slotId);
        if (slot == null) {
            throw new SlotNotFoundException(String.format("Slot with id [%d] not found in level [%d]", slotId, number));
        }
        if (slot.isOccupied()) {
            throw new RestrictedSlotOperationException(String.format("Slot with id [%d] in level [%d] is occupied and cannot be removed", slotId, number));
        }
        Slot removedSlot = slots.remove(slotId);
        return removedSlot;
    }

    public Optional<Slot> findAvailableSlot(Vehicle vehicle) {
        return slots.values().stream()
            .filter(Slot::isAvailable)
            .filter(slot -> isCompatible(slot, vehicle))
            .findFirst();
    }

    private boolean isCompatible(Slot slot, Vehicle vehicle) {
        return switch (vehicle.getType()) {
            case MOTORCYCLE -> true;
            case CAR -> slot.getType() != SlotType.MOTORCYCLE;
            case TRUCK -> slot.getType() == SlotType.LARGE;
        };
    }

    public int getNumber() {
        return number;
    }

    public Slot changeSlotStatus(Integer slotId, SlotStatus slotStatus) throws SlotNotFoundException, RestrictedSlotOperationException {
        Slot slot = slots.get(slotId);
        if (slot == null) {
            throw new SlotNotFoundException(String.format("Slot with id [%d] not found in level [%d]", slotId, number));
        }
        switch (slotStatus) {
            case AVAILABLE -> slot.release();
            case OCCUPIED -> slot.occupy();
            case UNAVAILABLE -> slot.markOutOfService();
        }
        return slot;
    }

    public Collection<Slot> getSlots() {
        return slots.values();
    }
}
